# Generated by Django 4.0.2 on 2022-05-02 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(default='uweflix\\static\\uweflix\\images\\placeholder.png', upload_to='uweflix\\static\\uweflix\\images'),
        ),
        migrations.AlterField(
            model_name='clubrep',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uweflix.club'),
        ),
    ]
