# Generated by Django 4.0.2 on 2022-05-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0003_alter_film_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(default='images/placeholder.png', upload_to='images/'),
        ),
    ]
