# Generated by Django 4.0.2 on 2023-05-02 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0009_alter_screen_apply_covid_restrictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_num_generator', models.IntegerField(blank=True, null=True)),
                ('first_initial', models.CharField(default='', max_length=1)),
                ('last_name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_year', models.IntegerField(default=2023)),
                ('expiry_month', models.CharField(default='', max_length=2)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflix.club')),
            ],
        ),
    ]
